import { User, Restaurant, Category, MenuItem, OrderWithItems, Feedback, Subscription } from './types';

export const INITIAL_USERS: User[] = [
  {
    id: 'usr-admin-01',
    name: 'Platform Super Admin',
    email: 'admin@demo.com',
    role: 'admin',
    created_at: new Date(Date.now() - 30 * 86400000).toISOString(),
  },
  {
    id: 'usr-owner-01',
    name: 'Marco Rossi',
    email: 'owner@demo.com',
    role: 'owner',
    created_at: new Date(Date.now() - 14 * 86400000).toISOString(),
  },
  {
    id: 'usr-owner-02',
    name: 'Kenji Sato',
    email: 'kenji@tokyoramen.com',
    role: 'owner',
    created_at: new Date(Date.now() - 10 * 86400000).toISOString(),
  },
  {
    id: 'usr-owner-03',
    name: 'Amelie Dubois',
    email: 'amelie@croissant.fr',
    role: 'owner',
    created_at: new Date(Date.now() - 5 * 86400000).toISOString(),
  },
  {
    id: 'usr-owner-04',
    name: 'Carlos Mendoza',
    email: 'carlos@urbantaco.com',
    role: 'owner',
    created_at: new Date(Date.now() - 2 * 86400000).toISOString(),
  }
];

export const INITIAL_RESTAURANTS: Restaurant[] = [
  {
    id: 'rst-01',
    owner_id: 'usr-owner-01',
    name: 'La Piazza Trattoria',
    slug: 'la-piazza',
    logo: 'https://images.unsplash.com/photo-1555396273-367ea4eb4db5?w=200&auto=format&fit=crop&q=80',
    address: '142 Via Della Spiga, Little Italy, NY 10013',
    phone: '+1 (212) 555-0199',
    opening_hours: 'Mon - Sun: 11:30 AM - 11:00 PM',
    description: 'Authentic rustic Italian trattoria specializing in handcrafted sourdough pizzas, fresh tagliatelle, and imported Italian wines.',
    subscription_status: 'active',
    created_at: new Date(Date.now() - 14 * 86400000).toISOString(),
  },
  {
    id: 'rst-02',
    owner_id: 'usr-owner-02',
    name: 'Tokyo Ramen House',
    slug: 'tokyo-ramen',
    logo: 'https://images.unsplash.com/photo-1569718212165-3a8278d5f624?w=200&auto=format&fit=crop&q=80',
    address: '742 Shibuya Crossing Blvd, San Francisco, CA 94103',
    phone: '+1 (415) 555-0842',
    opening_hours: 'Tue - Sun: 12:00 PM - 10:00 PM (Closed Mondays)',
    description: 'Slow-simmered 18-hour tonkotsu broth, handmade ramen noodles, and crispy gyoza.',
    subscription_status: 'active',
    created_at: new Date(Date.now() - 10 * 86400000).toISOString(),
  },
  {
    id: 'rst-03',
    owner_id: 'usr-owner-03',
    name: 'Le Petit Croissant Bistro',
    slug: 'le-petit-croissant',
    logo: 'https://images.unsplash.com/photo-1509440159596-0249088772ff?w=200&auto=format&fit=crop&q=80',
    address: '88 Boulevard Saint-Germain, Austin, TX 78701',
    phone: '+1 (512) 555-4921',
    opening_hours: 'Mon - Sat: 7:30 AM - 6:00 PM',
    description: 'Artisanal French bakery, flaky butter croissants, and Parisian cafe breakfast specials.',
    subscription_status: 'trialing',
    created_at: new Date(Date.now() - 5 * 86400000).toISOString(),
  },
  {
    id: 'rst-04',
    owner_id: 'usr-owner-04',
    name: 'Urban Taco & Cantina',
    slug: 'urban-taco',
    logo: 'https://images.unsplash.com/photo-1565299585323-38d6b0865b47?w=200&auto=format&fit=crop&q=80',
    address: '300 Mission St, Miami, FL 33101',
    phone: '+1 (305) 555-7731',
    opening_hours: 'Mon - Sun: 12:00 PM - 12:00 AM',
    description: 'Street-style gourmet tacos, fresh guacamole, and craft agave margaritas.',
    subscription_status: 'past_due',
    created_at: new Date(Date.now() - 2 * 86400000).toISOString(),
  }
];

export const INITIAL_SUBSCRIPTIONS: Subscription[] = [
  {
    id: 'sub-01',
    restaurant_id: 'rst-01',
    plan: 'Pro',
    start_date: new Date(Date.now() - 14 * 86400000).toISOString(),
    expiry_date: new Date(Date.now() + 350 * 86400000).toISOString(),
    status: 'active',
    created_at: new Date(Date.now() - 14 * 86400000).toISOString(),
  },
  {
    id: 'sub-02',
    restaurant_id: 'rst-02',
    plan: 'Enterprise',
    start_date: new Date(Date.now() - 10 * 86400000).toISOString(),
    expiry_date: new Date(Date.now() + 220 * 86400000).toISOString(),
    status: 'active',
    created_at: new Date(Date.now() - 10 * 86400000).toISOString(),
  },
  {
    id: 'sub-03',
    restaurant_id: 'rst-03',
    plan: 'Starter',
    start_date: new Date(Date.now() - 5 * 86400000).toISOString(),
    expiry_date: new Date(Date.now() + 9 * 86400000).toISOString(),
    status: 'trialing',
    created_at: new Date(Date.now() - 5 * 86400000).toISOString(),
  },
  {
    id: 'sub-04',
    restaurant_id: 'rst-04',
    plan: 'Growth',
    start_date: new Date(Date.now() - 40 * 86400000).toISOString(),
    expiry_date: new Date(Date.now() - 2 * 86400000).toISOString(),
    status: 'past_due',
    created_at: new Date(Date.now() - 40 * 86400000).toISOString(),
  }
];

export const INITIAL_CATEGORIES: Category[] = [
  {
    id: 'cat-01',
    restaurant_id: 'rst-01',
    name: 'Starters & Antipasti',
    created_at: new Date(Date.now() - 14 * 86400000).toISOString(),
  },
  {
    id: 'cat-02',
    restaurant_id: 'rst-01',
    name: 'Artisan Pizzas',
    created_at: new Date(Date.now() - 14 * 86400000).toISOString(),
  },
  {
    id: 'cat-03',
    restaurant_id: 'rst-01',
    name: 'Handmade Pastas',
    created_at: new Date(Date.now() - 14 * 86400000).toISOString(),
  },
  {
    id: 'cat-04',
    restaurant_id: 'rst-01',
    name: 'Desserts & Dolci',
    created_at: new Date(Date.now() - 14 * 86400000).toISOString(),
  },
  {
    id: 'cat-05',
    restaurant_id: 'rst-01',
    name: 'Beverages',
    created_at: new Date(Date.now() - 14 * 86400000).toISOString(),
  }
];

export const INITIAL_MENU_ITEMS: MenuItem[] = [
  {
    id: 'item-01',
    restaurant_id: 'rst-01',
    category_id: 'cat-01',
    name: 'Bruschetta al Pomodoro',
    description: 'Toasted sourdough bread, heirloom tomatoes, fresh sweet basil, garlic, and aged balsamic glaze.',
    price: 12.50,
    image: 'https://images.unsplash.com/photo-1572695157366-5e585ab2b69f?w=500&auto=format&fit=crop&q=80',
    available: true,
    is_veg: true,
    dietary_type: 'vegan',
    created_at: new Date(Date.now() - 14 * 86400000).toISOString(),
  },
  {
    id: 'item-02',
    restaurant_id: 'rst-01',
    category_id: 'cat-01',
    name: 'Burrata Pugliese',
    description: 'Creamy fresh burrata cheese, heirloom tomatoes, wild baby arugula, and extra virgin olive oil.',
    price: 16.00,
    image: 'https://images.unsplash.com/photo-1592417817098-8f3d6eb22509?w=500&auto=format&fit=crop&q=80',
    available: true,
    is_veg: true,
    dietary_type: 'veg',
    created_at: new Date(Date.now() - 14 * 86400000).toISOString(),
  },
  {
    id: 'item-03',
    restaurant_id: 'rst-01',
    category_id: 'cat-02',
    name: 'Margherita D.O.P.',
    description: 'San Marzano tomato sauce, fior di latte mozzarella, fresh basil leaves, and cold-pressed olive oil.',
    price: 18.50,
    image: 'https://images.unsplash.com/photo-1604382355076-af4b0eb60143?w=500&auto=format&fit=crop&q=80',
    available: true,
    is_veg: true,
    dietary_type: 'veg',
    created_at: new Date(Date.now() - 14 * 86400000).toISOString(),
  },
  {
    id: 'item-04',
    restaurant_id: 'rst-01',
    category_id: 'cat-02',
    name: 'Truffle & Wild Mushroom Pizza',
    description: 'Black truffle cream, roasted shiitake and cremini mushrooms, fontina cheese, and fresh thyme.',
    price: 24.00,
    image: 'https://images.unsplash.com/photo-1513104890138-7c749659a591?w=500&auto=format&fit=crop&q=80',
    available: true,
    is_veg: true,
    dietary_type: 'veg',
    created_at: new Date(Date.now() - 14 * 86400000).toISOString(),
  },
  {
    id: 'item-05',
    restaurant_id: 'rst-01',
    category_id: 'cat-03',
    name: 'Tagliatelle al Tartufo',
    description: 'Hand-rolled egg tagliatelle, black summer truffles, creamy butter sauce, and 24-month Parmigiano-Reggiano.',
    price: 26.00,
    image: 'https://images.unsplash.com/photo-1551183053-bf91a1d81141?w=500&auto=format&fit=crop&q=80',
    available: true,
    is_veg: true,
    dietary_type: 'veg',
    created_at: new Date(Date.now() - 14 * 86400000).toISOString(),
  },
  {
    id: 'item-06',
    restaurant_id: 'rst-01',
    category_id: 'cat-03',
    name: 'Classic Lasagna Bolognese',
    description: 'Layered fresh pasta sheets, slow-braised beef ragu, creamy bechamel, and melted mozzarella.',
    price: 22.00,
    image: 'https://images.unsplash.com/photo-1574894709920-11b28e7367e3?w=500&auto=format&fit=crop&q=80',
    available: false,
    is_veg: false,
    dietary_type: 'non-veg',
    created_at: new Date(Date.now() - 14 * 86400000).toISOString(),
  },
  {
    id: 'item-07',
    restaurant_id: 'rst-01',
    category_id: 'cat-04',
    name: 'Tiramisu Tradizionale',
    description: 'Espresso-soaked Savoiardi ladyfingers, mascarpone sabayon, and Dutch dark cocoa dusting.',
    price: 9.50,
    image: 'https://images.unsplash.com/photo-1571877227200-a0d98ea607e9?w=500&auto=format&fit=crop&q=80',
    available: true,
    is_veg: true,
    dietary_type: 'veg',
    created_at: new Date(Date.now() - 14 * 86400000).toISOString(),
  },
  {
    id: 'item-08',
    restaurant_id: 'rst-01',
    category_id: 'cat-05',
    name: 'San Pellegrino Sparkling (750ml)',
    description: 'Imported natural sparkling mineral water from the Italian Alps.',
    price: 5.50,
    image: 'https://images.unsplash.com/photo-1527661591475-527312dd65f5?w=500&auto=format&fit=crop&q=80',
    available: true,
    is_veg: true,
    dietary_type: 'vegan',
    created_at: new Date(Date.now() - 14 * 86400000).toISOString(),
  }
];

export const INITIAL_ORDERS: OrderWithItems[] = [
  {
    id: 'ord-01',
    restaurant_id: 'rst-01',
    table_number: 'Table 4',
    customer_notes: 'Please cut pizzas into 8 slices. Extra napkins please!',
    status: 'pending',
    total_amount: 42.50,
    created_at: new Date(Date.now() - 3 * 60000).toISOString(),
    items: [
      {
        id: 'oi-01',
        order_id: 'ord-01',
        menu_item_id: 'item-03',
        name: 'Margherita D.O.P.',
        quantity: 2,
        price: 18.50,
        created_at: new Date(Date.now() - 3 * 60000).toISOString(),
      },
      {
        id: 'oi-02',
        order_id: 'ord-01',
        menu_item_id: 'item-08',
        name: 'San Pellegrino Sparkling (750ml)',
        quantity: 1,
        price: 5.50,
        created_at: new Date(Date.now() - 3 * 60000).toISOString(),
      }
    ]
  },
  {
    id: 'ord-02',
    restaurant_id: 'rst-01',
    table_number: 'Table 12',
    customer_notes: 'Extra freshly shaved black truffles if possible.',
    status: 'preparing',
    total_amount: 42.00,
    created_at: new Date(Date.now() - 10 * 60000).toISOString(),
    items: [
      {
        id: 'oi-03',
        order_id: 'ord-02',
        menu_item_id: 'item-05',
        name: 'Tagliatelle al Tartufo',
        quantity: 1,
        price: 26.00,
        created_at: new Date(Date.now() - 10 * 60000).toISOString(),
      },
      {
        id: 'oi-04',
        order_id: 'ord-02',
        menu_item_id: 'item-02',
        name: 'Burrata Pugliese',
        quantity: 1,
        price: 16.00,
        created_at: new Date(Date.now() - 10 * 60000).toISOString(),
      }
    ]
  },
  {
    id: 'ord-03',
    restaurant_id: 'rst-01',
    table_number: 'Table 7',
    customer_notes: '',
    status: 'ready',
    total_amount: 33.50,
    created_at: new Date(Date.now() - 18 * 60000).toISOString(),
    items: [
      {
        id: 'oi-05',
        order_id: 'ord-03',
        menu_item_id: 'item-04',
        name: 'Truffle & Wild Mushroom Pizza',
        quantity: 1,
        price: 24.00,
        created_at: new Date(Date.now() - 18 * 60000).toISOString(),
      },
      {
        id: 'oi-06',
        order_id: 'ord-03',
        menu_item_id: 'item-07',
        name: 'Tiramisu Tradizionale',
        quantity: 1,
        price: 9.50,
        created_at: new Date(Date.now() - 18 * 60000).toISOString(),
      }
    ]
  },
  {
    id: 'ord-04',
    restaurant_id: 'rst-01',
    table_number: 'Table 2',
    customer_notes: 'Celebration dinner',
    status: 'completed',
    total_amount: 31.00,
    created_at: new Date(Date.now() - 55 * 60000).toISOString(),
    items: [
      {
        id: 'oi-07',
        order_id: 'ord-04',
        menu_item_id: 'item-01',
        name: 'Bruschetta al Pomodoro',
        quantity: 1,
        price: 12.50,
        created_at: new Date(Date.now() - 55 * 60000).toISOString(),
      },
      {
        id: 'oi-08',
        order_id: 'ord-04',
        menu_item_id: 'item-03',
        name: 'Margherita D.O.P.',
        quantity: 1,
        price: 18.50,
        created_at: new Date(Date.now() - 55 * 60000).toISOString(),
      }
    ]
  }
];

export const INITIAL_FEEDBACK: Feedback[] = [
  {
    id: 'fb-01',
    restaurant_id: 'rst-01',
    order_id: 'ord-04',
    customer_name: 'Sophia Martinez',
    rating: 5,
    comment: 'The Margherita pizza had the most incredible crispy crust and fresh basil. QR ordering directly from our table was super fast and seamless!',
    created_at: new Date(Date.now() - 40 * 60000).toISOString(),
  },
  {
    id: 'fb-02',
    restaurant_id: 'rst-01',
    order_id: null,
    customer_name: 'David Chen',
    rating: 5,
    comment: 'Truffle & Wild Mushroom pizza is absolute perfection. 10/10 culinary experience. Will definitely be bringing friends back here.',
    created_at: new Date(Date.now() - 2.5 * 3600000).toISOString(),
  },
  {
    id: 'fb-03',
    restaurant_id: 'rst-01',
    order_id: null,
    customer_name: 'Elena Rostova',
    rating: 5,
    comment: 'Tagliatelle al Tartufo was melt-in-your-mouth creamy! We loved being able to track the cooking progress on our phones in real time.',
    created_at: new Date(Date.now() - 4.5 * 3600000).toISOString(),
  },
  {
    id: 'fb-04',
    restaurant_id: 'rst-01',
    order_id: null,
    customer_name: 'Liam Gallagher',
    rating: 4,
    comment: 'Delicious Burrata appetizer and great authentic ambiance. Food came out steaming hot in under 12 minutes.',
    created_at: new Date(Date.now() - 24 * 3600000).toISOString(),
  },
  {
    id: 'fb-05',
    restaurant_id: 'rst-01',
    order_id: null,
    customer_name: 'Chloe Bennett',
    rating: 5,
    comment: 'Authentic Italian dining at its finest! The Tiramisu was light and heavenly.',
    created_at: new Date(Date.now() - 48 * 3600000).toISOString(),
  }
];

export const DEMO_ACCOUNTS = [
  {
    role: 'owner',
    title: 'Restaurant Owner Demo',
    email: 'owner@demo.com',
    password: 'password123',
    description: 'Manage "La Piazza Trattoria", accept live kitchen orders, inspect feedback & analytics',
    restaurantName: 'La Piazza Trattoria',
  },
  {
    role: 'admin',
    title: 'Super Admin Demo',
    email: 'admin@demo.com',
    password: 'password123',
    description: 'Full platform oversight, manage all tenants, toggle subscriptions',
    restaurantName: 'Platform Administration',
  }
];
